### ISSUE TITLE
[BLUEMARLIN-24] DL predictor for both ad requests and impressions

### ISSUE THREAD

**Issue by rangaswamymr** [apache/incubator-bluemarlin#44]
Dears, 
we have a requirement to use DL predictor to predict both ad requests and impressions in parallel and save the predictions of impressions and ad-requests into different output tables and elastic search indexes.  Can we discuss this feasibility today ?
is it possible to organize a meeting before Thursday's weekly meeting?

**Comment by radibnia77** [comment]
You need 2 pipelines to build 2 different models to predict each item.
1. DLPredictor Impression Pipeline
2. DLPredictor Request Pipeline

These pipelines are almost identical; the differences can me on
1. Different active modules, For example, the Request Pipeline has a transform module that modifies the schema of the Request Table so that it can be processed by existing modules; adding price-category and bucket-ids
2. Configuration; different input tables, pipeline tags and etc.
